version: 2
updates:
  # frontend npm用の更新
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - MASAKi-cell
    assignees:
      - MASAKi-cell
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    ignore: # バージョンアップの除外設定
      - dependency-name: "*"
        update-types:
          # メジャーバージョンは除外、本番運用している場合、気軽にupdateできない為
          - version-update:semver-major

  # backend: pipenv 用の更新
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      time: "00:00"
    open-pull-requests-limit: 10
    reviewers:
      - MASAKi-cell
    assignees:
      - MASAKi-cell
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
