version: "3.7"
services:
  backend:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
